package com.szxb.zibo.voice;

public class VoiceConfig {
    public static final int shangban = 1;
    public static final int xiaban = shangban + 1;
    public static final int erweimamiyaoguoqi = xiaban + 1;
    public static final int erweimaguoqi = erweimamiyaoguoqi + 1;
    public static final int erweimageshicuowu = erweimaguoqi + 1;
    public static final int erweimachongfushiyong = erweimageshicuowu + 1;
    public static final int yuebuzu = erweimachongfushiyong + 1;
    public static final int rongjunka = yuebuzu + 1;
    public static final int heimingdanka = rongjunka + 1;
    public static final int yinhangshanfuka = heimingdanka + 1;
    public static final int qingchongshua = yinhangshanfuka + 1;
    public static final int qingnianshen = qingchongshua + 1;
    public static final int qingchongzhi = qingnianshen + 1;
    public static final int laonianka = qingchongzhi + 1;
    public static final int xianluka = laonianka + 1;
    public static final int aixinka = xianluka + 1;
    public static final int cikayiguoyouxiaoqi = aixinka + 1;
    public static final int zanshibunengshiyong = cikayiguoyouxiaoqi + 1;
    public static final int xueshengka = zanshibunengshiyong + 1;
    public static final int shixiaoka = xueshengka + 1;
    public static final int yuangongka = shixiaoka + 1;
    public static final int sijika = yuangongka + 1;
    public static final int shuamachenggong = sijika + 1;
    public static final int ec_fee = shuamachenggong + 1;
    public static final int ic_invalid = ec_fee + 1;
    public static final int saomashibai = ic_invalid + 1;
    public static final int wuxiaoma = saomashibai + 1;
    public static final int qingshuaxinchongsao = wuxiaoma + 1;
    public static final int zanshibunengshiyongcifangshijiaoyi = qingshuaxinchongsao + 1;
    public static final int xitongyichang = zanshibunengshiyongcifangshijiaoyi + 1;
    public static final int didi = xitongyichang + 1;


    public static final int caijika = didi + 1;
    public static final int qiandianka = caijika + 1;
    public static final int jianceka = qiandianka + 1;
    public static final int chongzhiyuanshouquancaozuoka = jianceka + 1;
    public static final int chengxuxiazaishouquanka = chongzhiyuanshouquancaozuoka + 1;
    public static final int chuzucheshujucaijika = chengxuxiazaishouquanka + 1;
    public static final int jiayouka = chuzucheshujucaijika + 1;
    public static final int wuchangxianxueka = jiayouka + 1;
    public static final int dang = wuchangxianxueka + 1;
    public static final int dangdang = dang + 1;
    public static final int cuowu = dangdang + 1;
    public static final int qingshangche = cuowu + 1;
    public static final int qingxiache = qingshangche + 1;
    public static final int bupiao = qingxiache + 1;
    public static final int sijiweishangban = bupiao + 1;
    public static final int qingxiacheqingchongzhi = sijiweishangban + 1;
    public static final int xueshenkaqingxiache = qingxiacheqingchongzhi + 1;
    public static final int laoniankaqingxiache = xueshenkaqingxiache + 1;
    public static final int aixinkaqingxiache = laoniankaqingxiache + 1;
    public static final int rongjunkaqinngxiache = aixinkaqingxiache + 1;
    public static final int xueshengkaqingshangche = rongjunkaqinngxiache + 1;
    public static final int laoniankaqingshangche = xueshengkaqingshangche + 1;
    public static final int aixinkaqingshangche = laoniankaqingshangche + 1;
    public static final int rongjunkaqingshangche = aixinkaqingshangche + 1;
}
