package com.szxb.zibo.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.szxb.zibo.config.zibo.line.ContinuousRule;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTINUOUS_RULE".
*/
public class ContinuousRuleDao extends AbstractDao<ContinuousRule, Void> {

    public static final String TABLENAME = "CONTINUOUS_RULE";

    /**
     * Properties of entity ContinuousRule.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property LineNum = new Property(0, String.class, "lineNum", false, "LINE_NUM");
        public final static Property StationNum = new Property(1, String.class, "stationNum", false, "STATION_NUM");
        public final static Property Longitude = new Property(2, String.class, "longitude", false, "LONGITUDE");
        public final static Property Latitude = new Property(3, String.class, "latitude", false, "LATITUDE");
    }


    public ContinuousRuleDao(DaoConfig config) {
        super(config);
    }
    
    public ContinuousRuleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTINUOUS_RULE\" (" + //
                "\"LINE_NUM\" TEXT," + // 0: lineNum
                "\"STATION_NUM\" TEXT," + // 1: stationNum
                "\"LONGITUDE\" TEXT," + // 2: longitude
                "\"LATITUDE\" TEXT);"); // 3: latitude
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTINUOUS_RULE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ContinuousRule entity) {
        stmt.clearBindings();
 
        String lineNum = entity.getLineNum();
        if (lineNum != null) {
            stmt.bindString(1, lineNum);
        }
 
        String stationNum = entity.getStationNum();
        if (stationNum != null) {
            stmt.bindString(2, stationNum);
        }
 
        String longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindString(3, longitude);
        }
 
        String latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindString(4, latitude);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ContinuousRule entity) {
        stmt.clearBindings();
 
        String lineNum = entity.getLineNum();
        if (lineNum != null) {
            stmt.bindString(1, lineNum);
        }
 
        String stationNum = entity.getStationNum();
        if (stationNum != null) {
            stmt.bindString(2, stationNum);
        }
 
        String longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindString(3, longitude);
        }
 
        String latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindString(4, latitude);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ContinuousRule readEntity(Cursor cursor, int offset) {
        ContinuousRule entity = new ContinuousRule( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // lineNum
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // stationNum
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // longitude
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // latitude
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ContinuousRule entity, int offset) {
        entity.setLineNum(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setStationNum(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLongitude(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLatitude(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ContinuousRule entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ContinuousRule entity) {
        return null;
    }

    @Override
    public boolean hasKey(ContinuousRule entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
