package com.szxb.zibo.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.szxb.zibo.moudle.function.unionpay.entity.UnionAidEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "UNION_AID_ENTITY".
*/
public class UnionAidEntityDao extends AbstractDao<UnionAidEntity, Long> {

    public static final String TABLENAME = "UNION_AID_ENTITY";

    /**
     * Properties of entity UnionAidEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IcParam = new Property(1, String.class, "icParam", false, "IC_PARAM");
        public final static Property Reserve = new Property(2, String.class, "reserve", false, "RESERVE");
    }


    public UnionAidEntityDao(DaoConfig config) {
        super(config);
    }
    
    public UnionAidEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"UNION_AID_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"IC_PARAM\" TEXT UNIQUE ," + // 1: icParam
                "\"RESERVE\" TEXT);"); // 2: reserve
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"UNION_AID_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UnionAidEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String icParam = entity.getIcParam();
        if (icParam != null) {
            stmt.bindString(2, icParam);
        }
 
        String reserve = entity.getReserve();
        if (reserve != null) {
            stmt.bindString(3, reserve);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UnionAidEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String icParam = entity.getIcParam();
        if (icParam != null) {
            stmt.bindString(2, icParam);
        }
 
        String reserve = entity.getReserve();
        if (reserve != null) {
            stmt.bindString(3, reserve);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UnionAidEntity readEntity(Cursor cursor, int offset) {
        UnionAidEntity entity = new UnionAidEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // icParam
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // reserve
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UnionAidEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIcParam(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setReserve(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UnionAidEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UnionAidEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UnionAidEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
