package com.szxb.zibo.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.szxb.zibo.config.haikou.Whitelist;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WHITELIST".
*/
public class WhitelistDao extends AbstractDao<Whitelist, Long> {

    public static final String TABLENAME = "WHITELIST";

    /**
     * Properties of entity Whitelist.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User = new Property(1, String.class, "user", false, "USER");
        public final static Property Cardno = new Property(2, String.class, "cardno", false, "CARDNO");
        public final static Property DeadCardno = new Property(3, String.class, "deadCardno", false, "DEAD_CARDNO");
        public final static Property Level = new Property(4, String.class, "level", false, "LEVEL");
        public final static Property Password = new Property(5, String.class, "password", false, "PASSWORD");
    }


    public WhitelistDao(DaoConfig config) {
        super(config);
    }
    
    public WhitelistDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WHITELIST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER\" TEXT," + // 1: user
                "\"CARDNO\" TEXT UNIQUE ," + // 2: cardno
                "\"DEAD_CARDNO\" TEXT," + // 3: deadCardno
                "\"LEVEL\" TEXT," + // 4: level
                "\"PASSWORD\" TEXT);"); // 5: password
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WHITELIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Whitelist entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String user = entity.getUser();
        if (user != null) {
            stmt.bindString(2, user);
        }
 
        String cardno = entity.getCardno();
        if (cardno != null) {
            stmt.bindString(3, cardno);
        }
 
        String deadCardno = entity.getDeadCardno();
        if (deadCardno != null) {
            stmt.bindString(4, deadCardno);
        }
 
        String level = entity.getLevel();
        if (level != null) {
            stmt.bindString(5, level);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(6, password);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Whitelist entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String user = entity.getUser();
        if (user != null) {
            stmt.bindString(2, user);
        }
 
        String cardno = entity.getCardno();
        if (cardno != null) {
            stmt.bindString(3, cardno);
        }
 
        String deadCardno = entity.getDeadCardno();
        if (deadCardno != null) {
            stmt.bindString(4, deadCardno);
        }
 
        String level = entity.getLevel();
        if (level != null) {
            stmt.bindString(5, level);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(6, password);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Whitelist readEntity(Cursor cursor, int offset) {
        Whitelist entity = new Whitelist( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // user
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cardno
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // deadCardno
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // level
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // password
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Whitelist entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCardno(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDeadCardno(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLevel(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPassword(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Whitelist entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Whitelist entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Whitelist entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
